

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: get-urls

jobs:
  get-urls:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Get update list
        run: Rscript -e 'source("R/get-filepaths.R", echo = TRUE); writefile(get_filepaths())'



      - name: Commit
        run: |
          git config --global user.name 'Michael Sumner'
          git config --global user.email 'mdsumner@gmail.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"
